# Generated by Django 6.0 on 2025-12-26 09:23

import apps.account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.account.models.status_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
