# Generated by Django 6.0 on 2025-12-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HaulingCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.PositiveIntegerField(editable=False)),
                ('message_year', models.PositiveIntegerField(editable=False)),
                ('message_month', models.PositiveSmallIntegerField(editable=False)),
                ('load', models.CharField(choices=[('1', 'Coal'), ('2', 'Over Burden'), ('3', 'Etc'), ('4', 'No Load')], default='1', max_length=50)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyMessageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
