# Generated by Django 6.0 on 2025-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulingcheckrecord',
            name='status',
            field=models.CharField(choices=[('1', 'IN'), ('2', 'OUT')], default='1', max_length=5),
        ),
    ]
