# Generated by Django 6.0 on 2025-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=50)),
                ('code', models.PositiveIntegerField()),
                ('tara', models.PositiveIntegerField()),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
    ]
