# Generated by Django 6.0 on 2025-12-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
