# Generated by Django 6.0 on 2025-12-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_unit_prefix_alter_unit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='brand',
            field=models.CharField(choices=[('HINO', 'HINO'), ('MERCEDEZ BANZ', 'MERCEDEZ BANZ'), ('SCANIA', 'SCANIA'), ('DONGFENG', 'DONGFENG'), ('FOTON', 'FOTON')], default='HINO', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('KPN', 'KPN'), ('MBLE', 'MBLE'), ('WWPI', 'WWPI'), ('BBS', 'BBS'), ('MJR', 'MJR')], default='KPN', max_length=25),
        ),
        migrations.AlterField(
            model_name='unit',
            name='prefix',
            field=models.CharField(choices=[('KPNDT', 'KPNDT'), ('DTMB', 'DTMB'), ('DTWG', 'DTWG'), ('BSDT', 'BSDT'), ('MJRDT', 'MJRDT')], default='KPNDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='tara',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
